### ISSUE TITLE
[Tracking Issue] Wider Feedback Round

### ISSUE THREAD

**Issue by rylev** [rust-lang/surveys#63]
This is a tracking issue for the items we want to get done before moving to actively seeking out feedback from others on the annual survey (tracked by issue #3)

- [ ] Get feedback from previous authors of the Rust annual survey
- [ ] Do a pass over the previous years survey to make sure we didn't leave out a question just because we forgot
- [ ] Close or make progress on [blocking open issues](https://github.com/rust-lang/surveys/issues?q=is%3Aissue+is%3Aopen+label%3Ablocking+label%3Aannual-survey)
